### ISSUE TITLE
Code specific to single machine

### ISSUE THREAD

**Issue by kunalchelani** [ZacharyTaylor/ICRA2015-Calibration-Code#1]
Do you plan to release a more generic version of the code that is  machine agnostic. For example I have CUDA 8.0 installed and I am working on MATLAB16a, whereas the mex files have been compiled with CUDA 6.0 and there isnt any simple config file to do change the version. 
If not, can you guide on what all changes need to be made to perform this.

**Comment by ZacharyTaylor** [comment]
The makefile I used for compiling is located at https://github.com/ZacharyTaylor/ICRA2015-Calibration-Code/blob/master/imageMetric/mex%20source/makefile

Hopefully compiling for a new system would be as simple as changing the MATLABHOME and 
CUDAHOME  variables.

**Comment by kunalchelani** [comment]
Thanks for the prompt reply.

I tried
​the same thing before your comment, but I still do get an error for
GLIBCXX_3.4.21. I think this version is a requisite and not something that
can picked up from the system version status. I have updated the libstd to
the newer version and I have it in my /usr/lib/x86_64-linux-gnu whereas the
mex file keeps searching for it inside the $MATLABHOME/sys/os/glnxa64
directory. I have added the path to the latest version in the environment
variable $LD_LIBRARY_PATH, but Matlab still searches for it inside its own
directory. I know this isnt much of a code related issue, but if you have
any leads, I will really appreciate it. Thanks :)​

**Comment by kunalchelani** [comment]
For anyone else experiencing the same issue, there is a simple solution to force Matlab to use the correct version of libstdc++. Just use the following command to launch matlab:
LD_PRELOAD="path/to/correct/version/of/libstdc++" matab.
